use std::{
    env,
    fs::File,
    io::{BufWriter, Write},
    ops::RangeInclusive,
    path::{Path, PathBuf},
};

use amrex_rs::{
    IsosurfaceMethod, IsosurfaceOptions, Mesh3D, PlotFile, Sample, Surface, isosurface,
};
use anyhow::{Context, Result, bail, ensure};

struct Args {
    plotfile: PathBuf,
    variable: String,
    isovalue: f64,
    output: PathBuf,
    samples: Vec<(String, RangeInclusive<f64>)>,
    method: IsosurfaceMethod,
}

fn usage(program: &str) -> String {
    format!(
        "Usage: {program} <plotfile> <variable> <isovalue> <output.obj> [options]\n\
         \n\
         Options:\n\
           --sample <variable> <min> <max>  Map a quantity to U or V (repeat at most twice)\n\
           --method <mc33|rmt>               Extraction method [default: mc33]\n\
           --regularization <fraction>       RMT endpoint snap fraction [default: 0.25]\n\
           -h, --help                       Show this help"
    )
}

fn parse_args() -> Result<Option<Args>> {
    let mut values = env::args();
    let program = values.next().unwrap_or_else(|| "isosurface".to_string());
    let values = values.collect::<Vec<_>>();

    if values
        .iter()
        .any(|value| value == "-h" || value == "--help")
    {
        println!("{}", usage(&program));
        return Ok(None);
    }
    ensure!(values.len() >= 4, "{}", usage(&program));

    let plotfile = PathBuf::from(&values[0]);
    let variable = values[1].clone();
    let isovalue = values[2]
        .parse::<f64>()
        .with_context(|| format!("invalid isovalue {:?}", values[2]))?;
    let output = PathBuf::from(&values[3]);
    let mut samples = Vec::new();
    let mut method = "mc33";
    let mut regularization = 0.25_f32;
    let mut index = 4;

    while index < values.len() {
        match values[index].as_str() {
            "--sample" => {
                ensure!(
                    index + 3 < values.len(),
                    "--sample requires VARIABLE MIN MAX"
                );
                ensure!(samples.len() < 2, "--sample may be specified at most twice");
                let name = values[index + 1].clone();
                let min = values[index + 2]
                    .parse::<f64>()
                    .with_context(|| format!("invalid sample minimum {:?}", values[index + 2]))?;
                let max = values[index + 3]
                    .parse::<f64>()
                    .with_context(|| format!("invalid sample maximum {:?}", values[index + 3]))?;
                samples.push((name, min..=max));
                index += 4;
            }
            "--regularization" => {
                ensure!(
                    index + 1 < values.len(),
                    "--regularization requires a fraction"
                );
                regularization = values[index + 1].parse::<f32>().with_context(|| {
                    format!("invalid regularization fraction {:?}", values[index + 1])
                })?;
                index += 2;
            }
            "--method" => {
                ensure!(index + 1 < values.len(), "--method requires mc33 or rmt");
                method = values[index + 1].as_str();
                ensure!(
                    matches!(method, "mc33" | "rmt"),
                    "unknown method {method:?}"
                );
                index += 2;
            }
            option => bail!("unknown option {option:?}\n{}", usage(&program)),
        }
    }

    Ok(Some(Args {
        plotfile,
        variable,
        isovalue,
        output,
        samples,
        method: match method {
            "mc33" => IsosurfaceMethod::Mc33,
            "rmt" => IsosurfaceMethod::Rmt { regularization },
            _ => unreachable!(),
        },
    }))
}

fn component_id(plotfile: &PlotFile, name: &str) -> Result<u32> {
    let variable = plotfile
        .variable(name)
        .with_context(|| format!("plotfile has no variable named {name:?}"))?;
    u32::try_from(variable.index).context("variable index does not fit in u32")
}

fn write_obj(path: &Path, mesh: &Mesh3D, write_uvs: bool) -> Result<()> {
    let file = File::create(path).with_context(|| format!("creating {}", path.display()))?;
    let mut output = BufWriter::new(file);
    writeln!(output, "# generated by amrex_rs isosurface")?;

    for vertex in &mesh.positions {
        writeln!(
            output,
            "v {} {} {}",
            vertex.position.x, vertex.position.y, vertex.position.z
        )?;
    }
    if write_uvs {
        let scale = 1.0 / f64::from(u16::MAX);
        for vertex in &mesh.positions {
            writeln!(
                output,
                "vt {} {}",
                f64::from(vertex.sampled_values.x) * scale,
                f64::from(vertex.sampled_values.y) * scale
            )?;
        }
    }

    for face in &mesh.faces {
        let indices = [
            u64::from(face.x) + 1,
            u64::from(face.y) + 1,
            u64::from(face.z) + 1,
        ];
        if write_uvs {
            writeln!(
                output,
                "f {0}/{0} {1}/{1} {2}/{2}",
                indices[0], indices[1], indices[2]
            )?;
        } else {
            writeln!(output, "f {} {} {}", indices[0], indices[1], indices[2])?;
        }
    }
    output.flush()?;
    Ok(())
}

fn main() -> Result<()> {
    let Some(args) = parse_args()? else {
        return Ok(());
    };
    let plotfile = PlotFile::open(&args.plotfile)
        .with_context(|| format!("opening plotfile {}", args.plotfile.display()))?;
    let surface_id = component_id(&plotfile, &args.variable)?;
    let sampled_quantities = args
        .samples
        .iter()
        .map(|(name, range)| {
            Ok(Sample {
                id: component_id(&plotfile, name)?,
                range: range.clone(),
            })
        })
        .collect::<Result<Vec<_>>>()?;

    let mesh = isosurface(
        &plotfile,
        IsosurfaceOptions {
            surface: Surface {
                id: surface_id,
                value: args.isovalue,
            },
            sampled_quantities,
            method: args.method,
        },
    )?;
    write_obj(&args.output, &mesh, !args.samples.is_empty())?;
    eprintln!(
        "wrote {} vertices and {} faces to {}",
        mesh.positions.len(),
        mesh.faces.len(),
        args.output.display()
    );
    Ok(())
}

#[cfg(test)]
mod tests {
    use std::fs;

    use amrex_rs::Vertex3D;
    use glam::{U16Vec2, UVec3, Vec3};

    use super::*;

    #[test]
    fn obj_writer_emits_vertices_uvs_and_matching_indices() {
        let path = env::temp_dir().join(format!("amrex_rs_obj_test_{}.obj", std::process::id()));
        let mesh = Mesh3D {
            positions: vec![
                Vertex3D {
                    position: Vec3::ZERO,
                    sampled_values: U16Vec2::ZERO,
                },
                Vertex3D {
                    position: Vec3::X,
                    sampled_values: U16Vec2::new(u16::MAX, 0),
                },
                Vertex3D {
                    position: Vec3::Y,
                    sampled_values: U16Vec2::new(0, u16::MAX),
                },
            ],
            faces: vec![UVec3::new(0, 1, 2)],
        };

        write_obj(&path, &mesh, true).unwrap();
        let text = fs::read_to_string(&path).unwrap();
        let _ = fs::remove_file(&path);
        assert!(text.contains("v 1 0 0\n"));
        assert!(text.contains("vt 1 0\n"));
        assert!(text.contains("f 1/1 2/2 3/3\n"));
    }
}
